### ISSUE TITLE
Actividad 6 práctica de entrevista cuestionarios

### ISSUE THREAD

**Issue by Litzy-lopez4** [SistemasTecTlaxiaco/actividad-6-practica-de-entrevista-cuestionarios-etc-equipo-de-melissa#2]
[ReporteEncuesta.pdf](https://github.com/SistemasTecTlaxiaco/actividad-6-practica-de-entrevista-cuestionarios-etc-equipo-de-melissa/files/9974647/ReporteEncuesta.pdf)

**Comment by Valentiin01** [comment]
Calificación  29

**Comment by Valentiin01** [comment]
Calificación 30

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
